apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8082       # The service's internal port (can be the same as the external port)
      targetPort: 8081 # The port on which your backend pods are listening
      nodePort: 30080  # The NodePort on which Kubernetes exposes the service externally
