version: '3.8'

services:
  recommendation_service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - HOST=0.0.0.0 # Override FLASK_HOST inside Docker
    volumes:
      - ./model:/app/model
