{
 "title": "Movie Recommendation",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(recommendation_latency_ms[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(recommendation_failed_request[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Click-Through Rate (CTR) / Precision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(watched_recommended[30d])\r\n/\r\nsum(recommendation_movie_count[30d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watch Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count(count_over_time(watched_recommended[30d]) > 0)\r\n/\r\ncount(count_over_time(recommendation_movie_count[30d]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(watched_recommended[30d])\r\n/\r\nsum(watched_movie[30d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Rating of Recommended Movies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "avg(recommended_rated[30d])", "legendFormat": "__auto" }
   ]
  }
 ]
}